---
config:
  map:
    default: |-
      version: v1
      sharing:
        timeSlicing:
          renameByDefault: true
          failRequestsGreaterThanOne: true
          resources:
            - name: nvidia.com/gpu
              replicas: 3